//program to generate number guessing game
#include<stdio.h>
#include<stdlib.h>
#include<time.h>
int main(){
    //use srand to generate different number everytime
    srand(time(NULL));
    int min=1;
    //num is random number generated by rand
    int num=rand()%100+1;
    int n;
    
    for(int i=1;i<=5;i++){
        printf("enter choice %d :",i);
        scanf("%d",&n);
        //if number matches user wins 
        if(n==num){
             printf("YAY you have won!");
             break;
        }
        // if attempts are left give hint     
        else if(i!=5){
            if(n<num) printf("Too  low! try higher number\n");
            else if(n>num) printf("Too high! Try lower number\n");
        }
        else continue;    
    }
    if (n!=num) printf("YOU LOST");
    return 0;
}